services:
 db:
  image: mysql
  container_name: mysql-db-test
  ports:
  - '3232:3306'
  environment:
   MYSQL_ROOT_PASSWORD: password
   MYSQL_ROOT_USERNAME: root
   MYSQL_DATABASE: Employee
   PGDATA: /data/postgres
  volumes:
  - db_data:/data/postgres
  networks:
  - jwtnet
 jwtService:
  container_name: jwt-spring-app
  image: infinityrawat/jwt-spring-app
  ports:
  - '8082:8082'
  environment:
   SPRING_PROFILES_ACTIVE: dops
   MYSQL_PORT: 3232
  depends_on: 
   - db
  networks:
   - jwtnet
volumes:
 db_data:
 
networks:
 jwtnet:
  driver: bridge
    
